Plan:
* Use linspace to produce a bunch of values at some intervals
* SMARTLY restrict values
* Try and make it make sense
* Code equations first!
* Could brute force with REAL values (restrict to range) or CALCULATE values (use equations from geometry)

## Equations
With credit to tables from _Design of Rockets and Space Launch Vehicles_
* Change in velocity: $$\Delta v = v_{eq}ln(\frac{m_0}{m_f}) = v_{eq}ln(mass\ ratio) = v_{eq}ln(\mu) = g_0 I_{sp}ln\mu$$
    * $g_0$ is Earth's standard gravity at sea level. Taken to be 9.80665 $m/s^2$
* Missing time to burn equation
* Mass fraction: $$\mu = \frac{initial\ mass}{final\ mass} = \frac{m_0}{m_f} = \frac{m_0}{m_0-m_p}$$ 
<br />
* Total Launch Weight (Propellant and shell - NOT payload):
$$W_L = 0.04 Ld^2$$ 
    * NOTE: lb, in, in
    * Can be used to calculate masses instead of using values
<br /><br />
* Body Structure vs. Launch Weight: $$W_{Body Structure}/W_{Launch Weight} = 0.22$$
    * Launch weight includes the propellant
    * Combine with Total launch weight equations

### SM3 Mass Fractions (Mf/Mo)
* First Stage: .376
* Second Stage: .612
* Third Stage: .604

### Range of Real Mass Fractions (Mf/Mo)
With credit to tables from _Design of Rockets and Space Launch Vehicles_
* First Stage: 
    * 0.0432 -> 0.1198
* Second Stage:
    * 0.0495 -> 0.1700
* Third Stage:
    * 0.0824 -> 0.1008

### Range of Isps
With credit to tables from _Design of Rockets and Space Launch Vehicles_
* 200 seconds to 250 seconds 
    * 250 seconds more applicable

In [1]:
import numpy as np


In [128]:
specific_impulse = 250 # seconds
g = 9.80665 # m / s^2
v_eq = g*specific_impulse
meters_to_inches = 39.3700787402 ## multiply to meters

## Calculating Delta V using range of actual values

In [4]:
#m0 / mf
mass_frac_first = 1/np.linspace(0.0400, 0.1200)
mass_frac_second = 1/np.linspace(.0450, 0.1700) 
mass_frac_third = 1/np.linspace(.0800, 0.1010)

In [20]:
max_mf1 = np.max(mass_frac_first)
max_mf2 = np.max(mass_frac_second)
max_mf3 = np.max(mass_frac_third)

In [16]:
deltav_first = np.log(mass_frac_first) * v_eq
deltav_second = np.log(mass_frac_second) * v_eq
deltav_third = np.log(mass_frac_third) * v_eq
deltav_total_max = np.max(deltav_first)+np.max(deltav_second)+np.max(deltav_third)

In [66]:
print(
"Unitless values.\nMax Mass Fraction\n"
    "\tFirst: ", max_mf1, "\n\tSecond: ", max_mf2, "\n\tThird: ", max_mf3)
print(
"\n\nUnits in meters per second.\nMax Delta V\n",
    "\tFirst: ", np.max(deltav_first), "\n\tSecond: ", np.max(deltav_second), "\n\tThird: ", np.max(deltav_third),
"\n\nTotal Delta V: ", deltav_total_max)

Unitless values.
Max Mass Fraction
	First:  25.0 
	Second:  22.22222222222222 
	Third:  12.5


Units in meters per second.
Max Delta V
 	First:  7891.597151985934 
	Second:  7602.832900331016 
	Third:  6192.234202426388 

Total Delta V:  21686.66425474334


## Calculating Delta V with Mass Equations

In [47]:
## Constants given in project

total_length = 10.0 * 39.3700787402
diameter = 1.0 * 39.3700787402 ## convert given meters to inches (final unit inches)

In [48]:
launch_weight = 0.04 * total_length * (diameter)*(diameter) ## pounds

In [49]:
print(launch_weight, "lbs")
print(launch_weight/2.205, "kg")

24409.497637972003 lbs
11070.066955996374 kg


In [90]:
## Lengths in ratio form
l1_ratio = np.linspace(0.1, 1, 100)
l2_ratio = np.linspace(0.1, 1, 100)
print(np.round(l1_ratio*10, 1)) ## lengths corresponding to l1's ratio, rounded to tenths

[ 1.   1.1  1.2  1.3  1.4  1.5  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2
  2.3  2.4  2.5  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5
  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.5  4.6  4.7
  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.5  5.6  5.7  5.8  5.9  6.
  6.1  6.2  6.3  6.4  6.5  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3
  7.4  7.5  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.5
  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.5  9.6  9.7  9.8
  9.9 10. ]


In [98]:
## Create new data type to hold a tuple in each element of the array (makes adding elements easier)
##length 1 ratio, length 2 ratio, length 3 ratio
dt = np.dtype([('l1r', np.float64), ('l2r', np.float64), ('l3r', np.float64)])

## Test dt to make sure it works as expected

test = np.array([(1,2,3), (1,3,4)], dtype = dt)

print(test)
np.append(test, np.array([(4.,4.,2.)], dtype = dt))


[(1., 2., 3.) (1., 3., 4.)]
[(1., 2., 3.) (1., 3., 4.)]


In [101]:
## Find all possible ratio combos between the three stages, put it in an np array of tuples
ratio_list = np.array([], dtype=dt )

for i in l1_ratio:
    for j in l2_ratio:
        if(i+j > 1):
            continue
        else:
            ratio_list = np.append(ratio_list, np.array([(i, j, 1-i-j)], dtype = dt)) 
    
    
    

In [127]:
## convert the np array of tuples to a more useful np array of 3 columns and each row representing a tuple of 
## the ratios
ratio_list_converted = np.array([])
for i in ratio_list:
    ratio_list_converted = np.append(ratio_list_converted, np.array([[i[0], i[1], i[2]]]))
    
ratio_list_converted = np.reshape(ratio_list_converted, (-1, 3)).astype(np.float64)

##np.set_printoptions(threshold=np.inf) - to see ENTIRE list
print(np.round(ratio_list_converted*10, 2), "\n")
print(ratio_list_converted.shape)

## 4005 different combinations!

[[1.   1.   8.  ]
 [1.   1.09 7.91]
 [1.   1.18 7.82]
 ...
 [8.91 1.   0.09]
 [8.91 1.09 0.  ]
 [9.   1.   0.  ]] 

(4005, 3)


In [137]:
##now we calculate masses

launch_weights = 0.04 * (10 * ratio_list_converted * meters_to_inches) * diameter * diameter ## lbs 

final_masses = launch_weights*.22 ## after losing the propellant

(4005, 3)

In [156]:
test1 = np.array([[0, 2], [4,5]])
print(np.sum(test1, axis = 1))

[2 9]


In [159]:
## now mass fractions - m0/mf

stage_1_mf = np.sum(launch_weights, axis = 1)/(np.sum(launch_weights[:, 1:2], axis=1) + final_masses[:, 0])

stage_2_mf = np.sum(launch_weights[:, 1:2], axis = 1)/(launch_weights[:, 2] + final_masses[:, 1])
## need to fix still!

print(stage_2_mf)

[0.8196721311 0.8064516129 0.7936507937 0.78125      0.7692307692
 0.7575757576 0.7462686567 0.7352941176 0.7246376812 0.7142857143
 0.7042253521 0.6944444444 0.6849315068 0.6756756757 0.6666666667
 0.6578947368 0.6493506494 0.641025641  0.6329113924 0.625
 0.6172839506 0.6097560976 0.6024096386 0.5952380952 0.5882352941
 0.5813953488 0.5747126437 0.5681818182 0.5617977528 0.5555555556
 0.5494505495 0.5434782609 0.5376344086 0.5319148936 0.5263157895
 0.5208333333 0.5154639175 0.5102040816 0.5050505051 0.5
 0.495049505  0.4901960784 0.4854368932 0.4807692308 0.4761904762
 0.4716981132 0.4672897196 0.462962963  0.4587155963 0.4545454545
 0.4504504505 0.4464285714 0.4424778761 0.4385964912 0.4347826087
 0.4310344828 0.4273504274 0.4237288136 0.4201680672 0.4166666667
 0.4132231405 0.4098360656 0.406504065  0.4032258065 0.4
 0.3968253968 0.3937007874 0.390625     0.3875968992 0.3846153846
 0.3816793893 0.3787878788 0.3759398496 0.3731343284 0.3703703704
 0.3676470588 0.3649635036 0.362318

In [ ]:
## now delta vs

In [ ]:
## and quickly sum for total delta vs